### ISSUE TITLE
Improve mapping of controller to robot actions

### ISSUE THREAD

**Issue by docprofsky** [TeamCautionRobotics/2016-FRC-robot#2]
We need to figure out and assign mapping the inputs on the controller to different robot actions.

**Comment by ConnorNail** [comment]
Driver Controller
- [x] Drive L Y Axis R Y Axis
- [x] Intake in Right Bumper
- [x] intake out Left Bumper
- [x] Slow drive Right Hold trigger
- [x] All out Left trigger

Partner Controller
- [x] Defense arm Left Y Axis
- [ ] Intake arm Right Y Axis
- [ ] Lift out hold Y button
- [ ] Lift in hold A button
- [x] Conveyor in Left Trigger
- [x] Conveyor out Left Bumper
- [x] Shooter Right Trigger
- [x] All out Hold B

**Comment by ConnorNail** [comment]
Functions:
- [x] All out
- [x] Intake in
- [x] Intake out
- [ ] Auto stop conveyor

**Comment by docprofsky** [comment]
Functions:
- [ ] Auto shoot spin up shooter and shoot ball

**Comment by docprofsky** [comment]
All out takes precedence over all other boulder system functions.

**Comment by docprofsky** [comment]
The current setup as of f70ce5e (unlikely to change):
Driver controller:
- Drive = both joysticks Y
- all out = left trigger
- Turn on targeting light = A

Partner controller:
- conveyor out = left bumper
- conveyor in = right bumper
- shooter fire = right trigger
- intake arm = left joystick Y
- intake roller = right joystick Y
- all out = B
